#!/bin/sh
# Sets the background. If given an argument, will set file as background.
[ ! -z "$1" ] && cp "$1" "$HOME/.config/wall" && notify-send -i "$HOME/.config/wall" "Wallpaper changed." \
&& xwallpaper --zoom ~/.config/wall
